/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EssenceClasses.Order;

import EssenceClasses.newpackage.Order;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import Check.Check;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Acer
 */
public class NewOrder extends javax.swing.JDialog {

    Connection c;
    Order editOrder;

    /**
     * Creates new form NewOrder
     *
     * @param parent
     * @param c
     * @param modal
     */
    public NewOrder(java.awt.Frame parent, boolean modal, Connection c) {
        super(parent, modal);
        initComponents();
        entryOrder();
        this.c = c;
    }

    public NewOrder(java.awt.Frame parent, boolean modal, Connection c, Order s) {
        super(parent, modal);
        initComponents();
        entryOrder();
        this.c = c;
        editOrder = s;
        fillFields();
    }
    public void entryOrder(){
        ((AbstractDocument) dateOrder.getDocument()).setDocumentFilter(new Check(10));
    }

    private void fillFields() {
        dateOrder.setText(editOrder.getDateOrder());
    }

    public boolean check() {
        if ("".equals(dateOrder.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Поле с датой приказа не должно быть пустым");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateOrder = new javax.swing.JTextField();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Дата приказа");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ok)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (!check()) {
            return;
        }
        try {
            Statement statement = c.createStatement();
            if (editOrder == null) {
                statement.executeUpdate(
                        "insert into \"order\" ("
                        + "date_order) "
                        + "values ('" + dateOrder.getText() + "');");
            } else {
                statement.executeUpdate("update \"order\" set date_order='"
                        + dateOrder.getText() + "' where id=" + editOrder.getId() + ";");
            }

        } catch (SQLException ex) {
            if (ex.getMessage().contains("State_Name_key")) {
                JOptionPane.showMessageDialog(new JFrame(), "This name already exist");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            }
            return;
        }
        dispose();
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
