/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EssenceClasses.Employee;

import java.sql.Connection;
import EssenceClasses.newpackage.Employee;
import Check.InputRestriction;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Acer
 */
public class NewEmployee extends javax.swing.JDialog {

    private Connection c;
    private Employee editEmployee;

    /**
     * Creates new form NewEmployee
     *
     * @param parent
     * @param modal
     * @param c
     */
    public NewEmployee(java.awt.Frame parent, boolean modal, Connection c) {
        super(parent, modal);
        initComponents();
        entryEmployee();
        this.c = c;

    }

    public NewEmployee(java.awt.Frame parent, boolean modal, Connection c, Employee e) {
        super(parent, modal);
        initComponents();
        entryEmployee();
        this.c = c;
        editEmployee = e;

        fillFields();
    }
    private void entryEmployee(){
        ((AbstractDocument) lastName.getDocument()).setDocumentFilter(new InputRestriction(32));
        ((AbstractDocument) name.getDocument()).setDocumentFilter(new InputRestriction(32));
        ((AbstractDocument) middleName.getDocument()).setDocumentFilter(new InputRestriction(32));
        ((AbstractDocument) dateBirth.getDocument()).setDocumentFilter(new InputRestriction(10));
        ((AbstractDocument) education.getDocument()).setDocumentFilter(new InputRestriction(32));
        ((AbstractDocument) dateWork.getDocument()).setDocumentFilter(new InputRestriction(10));
    }
    private void fillFields() {
        lastName.setText(editEmployee.getLastName());
        name.setText(editEmployee.getName());
        middleName.setText(editEmployee.getMiddleName());
        dateBirth.setText(editEmployee.getDateBirth());
        education.setText(editEmployee.getEducation());
        dateWork.setText(editEmployee.getDateOfWork());
    }

    private boolean check() {
        if ("".equals(lastName.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Поле с фамилией не должно быть пустым");
            return false;
        }
        if ("".equals(name.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Поле с именем не должно быть пустым");
            return false;
        }
        if ("".equals(dateWork.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Поле с датой принятия на работу не должно быть пустым");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        middleName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateBirth = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        education = new javax.swing.JTextField();
        dateWork = new javax.swing.JTextField();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Фамилия");

        jLabel2.setText("Имя");
        jLabel2.setToolTipText("");

        jLabel3.setText("Отчество");

        jLabel4.setText("Дата рождения");

        jLabel5.setText("Образование");

        jLabel6.setText("Дата принятия на работу");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(middleName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateBirth, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(education)
                    .addComponent(dateWork)
                    .addComponent(lastName, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(education, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ok)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (!check()) {
            return;
        }
        try {
            Statement statement = c.createStatement();
            if (editEmployee == null) {
                statement.executeUpdate(
                        "insert into employee (last_name,name,middle_name,"
                        + "date_birth,education,date_of_work) "
                        + "values ('" + lastName.getText() + "','"
                        + name.getText() + "','"
                        + middleName.getText() + "','"
                        + dateBirth.getText() + "','"
                        + education.getText() + "','"
                        + dateWork.getText() + "');");
            } else {
                statement.executeUpdate("update employee set last_name='"
                        + lastName.getText() + "',name='" + name.getText()
                        + "',middle_name='" + middleName.getText()
                        + "',date_birth='"
                        + dateBirth.getText() + "',education='"
                        + education.getText()
                        + "',date_of_work='" + dateWork.getText()
                        + "' where tab_number=" + editEmployee.getTabNumber() + ";");
            }

        } catch (SQLException ex) {
            if (ex.getMessage().contains("User_Login_key")) {
                JOptionPane.showMessageDialog(new JFrame(), "This login already exist");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            }
            return;
        }
        dispose();
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateBirth;
    private javax.swing.JTextField dateWork;
    private javax.swing.JTextField education;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField middleName;
    private javax.swing.JTextField name;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
